### ISSUE TITLE
Cube.js definitions attributes are case sensitive

### ISSUE THREAD

**Issue by olivierdupuis** [LewisCharlesBaker/droughty#15]
When generating Cube definitions, the supported attributes are case sensitive and will generate errors if they're all lowercase.

<img width="1073" alt="Screen Shot 2022-05-30 at 13 25 24" src="https://user-images.githubusercontent.com/20470/171038174-7a8a023c-0308-4536-9437-a04151f25274.png">

**Comment by LewisCharlesBaker** [comment]
Resolved in #20
