### ISSUE TITLE
The ability to extend the auto generated tests

### ISSUE THREAD

**Issue by sgeef** [LewisCharlesBaker/droughty#39]
Although the auto generated tests are an amazing start, they are not sufficient for proper testing and expectation change detection. 
Every data model is build on a set of assumptions that might chance over time, the only way to protect our data set's integrity would be to properly test for unexpected cases. 

In the current droughty project I don't believe there is any way to extend the auto generated tests with more advanced tests, adding this feature would add a lot to droughty.

**Comment by LewisCharlesBaker** [comment]
@sgeef - Thanks for raising this. I'm going to look into this over the next couple of weeks as I'm working on a feature that allows using to exclude certain tests

**Comment by LewisCharlesBaker** [comment]
@sgeef Find the documentation for the fix here https://droughty.readthedocs.io/en/latest/configuration.html
