### ISSUE TITLE
Suggestion: don't make test_overwrites overwrite all columns for model

### ISSUE THREAD

**Issue by Terroface** [LewisCharlesBaker/droughty#51]
The current setup makes the droughty_project.yaml file very and minimised automation value because for each table that needs at least one column overwrite, all columns will needed to be filled in. For the warehouse layer of one of our clients, that constitutes the whole warehouse layer, removing the benefit of the droughty automation.

Being able to overwrite just individual columns would constitute a much better workflow

**Comment by LewisCharlesBaker** [comment]
Resolved with PR #57
