### ISSUE TITLE
lkml - aggregate file's 'include:' should consider location of lookml subdir

### ISSUE THREAD

**Issue by Terroface** [LewisCharlesBaker/droughty#70]
<img width="890" alt="image" src="https://github.com/LewisCharlesBaker/droughty/assets/38318312/5a95f041-8b86-41fe-854f-fbf03140c406">
currently it overwrites the correct path when lookml is in a subdir^

**Comment by LewisCharlesBaker** [comment]
This should be resolved by https://github.com/LewisCharlesBaker/droughty/pull/72 please review
